# Generated by Django 5.1.4 on 2025-02-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_Birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disability',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
