# Generated by Django 5.1.4 on 2025-02-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Total_billed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
