# Generated by Django 5.1.4 on 2025-02-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
